mkdir the_right_into_duffus_dip
mkdir the_left_out_of_duffus_dip
mkdir mcintyre
mkdir butchers
mkdir railway_bend
mkdir taylors_hairpin
mkdir the_right_hander_before_charlies
mkdir charlies
mkdir park
mkdir chris_curve
mkdir gooseneck
mkdir mansfield
mkdir the_right_left_after_mansfield
mkdir the_left_right_before_the_mountain
mkdir halls_bend
mkdir barn
mkdir clervaux
mkdir hawthorn
mkdir tower
mkdir barcroft
mkdir sunny_in
mkdir sunny_out
mkdir the_start_of_the_complex
mkdir the_middle_of_the_complex
mkdir the_end_of_the_complex
mkdir old_hall
mkdir dentons
mkdir cascades
mkdir fosters
mkdir knickerbrook
mkdir lodge
mkdir deer_leap
mkdir lake_side
mkdir shell_oils_corner
mkdir brittens
mkdir island_hairpin
mkdir dunlop_curve
mkdir dunlop_chicane
mkdir tetre_rouge
mkdir playstation_chicane
mkdir michelin_chicane
mkdir mulsanne
mkdir indianapolis
mkdir arnage
mkdir porsche_curves
mkdir the_first_ford_chicane
mkdir the_second_ford_chicane
mkdir la_chapelle
mkdir le_musee
mkdir garage_vert
mkdir chemin_aux_boeufs
mkdir garage_bleu
mkdir raccodement
mkdir big_bend
mkdir lefthander
mkdir righthander
mkdir uphill
mkdir west_bend
mkdir downhill
mkdir uphill_chicane
mkdir west_bend_chicane
mkdir kristensen
mkdir fangio_chicane
mkdir cunningham
mkdir collier
mkdir bishop
mkdir gendebien
mkdir le_mans
mkdir sunset
mkdir rabbit
mkdir gurney
mkdir senna
mkdir wall_of_champions
mkdir anthony_noges
mkdir deene
mkdir yentwood
mkdir chapman_curve
mkdir pif_paf
mkdir gracelands
mkdir brook
mkdir senna_s
mkdir descida_do_lago
mkdir ferradura
mkdir pinheirinho
mkdir bico_do_pato
mkdir mergulho
mkdir juncao
mkdir riches
mkdir wilson
mkdir nelson
mkdir bomb_hole
mkdir coram
mkdir brundle
mkdir palmer
mkdir hamilton
mkdir agostini
mkdir oggies
mkdir murrays
mkdir old_paddock
mkdir williams
mkdir ratzenberger
mkdir bianchi
mkdir angel_bend
mkdir juliano_complex
mkdir scorpion
mkdir shuber_curves
mkdir snake








