//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrewChiefV4.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float background_volume {
            get {
                return ((float)(this["background_volume"]));
            }
            set {
                this["background_volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int update_interval {
            get {
                return ((int)(this["update_interval"]));
            }
            set {
                this["update_interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int minimum_time_between_pearls_of_wisdom {
            get {
                return ((int)(this["minimum_time_between_pearls_of_wisdom"]));
            }
            set {
                this["minimum_time_between_pearls_of_wisdom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool use_sweary_messages {
            get {
                return ((bool)(this["use_sweary_messages"]));
            }
            set {
                this["use_sweary_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool disable_immediate_messages {
            get {
                return ((bool)(this["disable_immediate_messages"]));
            }
            set {
                this["disable_immediate_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_spotter {
            get {
                return ((bool)(this["enable_spotter"]));
            }
            set {
                this["enable_spotter"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool log_temps {
            get {
                return ((bool)(this["log_temps"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string speech_recognition_location {
            get {
                return ((string)(this["speech_recognition_location"]));
            }
            set {
                this["speech_recognition_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.5")]
        public float r3e_spotter_car_length {
            get {
                return ((float)(this["r3e_spotter_car_length"]));
            }
            set {
                this["r3e_spotter_car_length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float spotter_gap_for_clear {
            get {
                return ((float)(this["spotter_gap_for_clear"]));
            }
            set {
                this["spotter_gap_for_clear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int time_after_race_start_for_spotter {
            get {
                return ((int)(this["time_after_race_start_for_spotter"]));
            }
            set {
                this["time_after_race_start_for_spotter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float min_speed_for_spotter {
            get {
                return ((float)(this["min_speed_for_spotter"]));
            }
            set {
                this["min_speed_for_spotter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int spotter_hold_repeat_frequency {
            get {
                return ((int)(this["spotter_hold_repeat_frequency"]));
            }
            set {
                this["spotter_hold_repeat_frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float max_closing_speed_for_spotter {
            get {
                return ((float)(this["max_closing_speed_for_spotter"]));
            }
            set {
                this["max_closing_speed_for_spotter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool spotter_only_when_being_passed {
            get {
                return ((bool)(this["spotter_only_when_being_passed"]));
            }
            set {
                this["spotter_only_when_being_passed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int spotter_clear_delay {
            get {
                return ((int)(this["spotter_clear_delay"]));
            }
            set {
                this["spotter_clear_delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int spotter_overlap_delay {
            get {
                return ((int)(this["spotter_overlap_delay"]));
            }
            set {
                this["spotter_overlap_delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_pearls_of_wisdom {
            get {
                return ((bool)(this["enable_pearls_of_wisdom"]));
            }
            set {
                this["enable_pearls_of_wisdom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int frequency_of_pearls_of_wisdom {
            get {
                return ((int)(this["frequency_of_pearls_of_wisdom"]));
            }
            set {
                this["frequency_of_pearls_of_wisdom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool play_cut_track_warnings {
            get {
                return ((bool)(this["play_cut_track_warnings"]));
            }
            set {
                this["play_cut_track_warnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int CHANNEL_OPEN_FUNCTION_button_index {
            get {
                return ((int)(this["CHANNEL_OPEN_FUNCTION_button_index"]));
            }
            set {
                this["CHANNEL_OPEN_FUNCTION_button_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CHANNEL_OPEN_FUNCTION_device_guid {
            get {
                return ((string)(this["CHANNEL_OPEN_FUNCTION_device_guid"]));
            }
            set {
                this["CHANNEL_OPEN_FUNCTION_device_guid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CHANNEL_OPEN_FUNCTION_device_type {
            get {
                return ((string)(this["CHANNEL_OPEN_FUNCTION_device_type"]));
            }
            set {
                this["CHANNEL_OPEN_FUNCTION_device_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int TOGGLE_RACE_UPDATES_FUNCTION_button_index {
            get {
                return ((int)(this["TOGGLE_RACE_UPDATES_FUNCTION_button_index"]));
            }
            set {
                this["TOGGLE_RACE_UPDATES_FUNCTION_button_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TOGGLE_RACE_UPDATES_FUNCTION_device_guid {
            get {
                return ((string)(this["TOGGLE_RACE_UPDATES_FUNCTION_device_guid"]));
            }
            set {
                this["TOGGLE_RACE_UPDATES_FUNCTION_device_guid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TOGGLE_RACE_UPDATES_FUNCTION_device_type {
            get {
                return ((string)(this["TOGGLE_RACE_UPDATES_FUNCTION_device_type"]));
            }
            set {
                this["TOGGLE_RACE_UPDATES_FUNCTION_device_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int TOGGLE_SPOTTER_FUNCTION_button_index {
            get {
                return ((int)(this["TOGGLE_SPOTTER_FUNCTION_button_index"]));
            }
            set {
                this["TOGGLE_SPOTTER_FUNCTION_button_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TOGGLE_SPOTTER_FUNCTION_device_guid {
            get {
                return ((string)(this["TOGGLE_SPOTTER_FUNCTION_device_guid"]));
            }
            set {
                this["TOGGLE_SPOTTER_FUNCTION_device_guid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TOGGLE_SPOTTER_FUNCTION_device_type {
            get {
                return ((string)(this["TOGGLE_SPOTTER_FUNCTION_device_type"]));
            }
            set {
                this["TOGGLE_SPOTTER_FUNCTION_device_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DISABLED")]
        public string VOICE_OPTION {
            get {
                return ((string)(this["VOICE_OPTION"]));
            }
            set {
                this["VOICE_OPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string custom_device_guid {
            get {
                return ((string)(this["custom_device_guid"]));
            }
            set {
                this["custom_device_guid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-applaunch 211500")]
        public string r3e_launch_params {
            get {
                return ((string)(this["r3e_launch_params"]));
            }
            set {
                this["r3e_launch_params"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/games/steam/steam.exe")]
        public string r3e_launch_exe {
            get {
                return ((string)(this["r3e_launch_exe"]));
            }
            set {
                this["r3e_launch_exe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool launch_raceroom {
            get {
                return ((bool)(this["launch_raceroom"]));
            }
            set {
                this["launch_raceroom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool run_immediately {
            get {
                return ((bool)(this["run_immediately"]));
            }
            set {
                this["run_immediately"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float messages_volume {
            get {
                return ((float)(this["messages_volume"]));
            }
            set {
                this["messages_volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_tyre_temp_warnings {
            get {
                return ((bool)(this["enable_tyre_temp_warnings"]));
            }
            set {
                this["enable_tyre_temp_warnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_race_start_messages {
            get {
                return ((bool)(this["enable_race_start_messages"]));
            }
            set {
                this["enable_race_start_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_fuel_messages {
            get {
                return ((bool)(this["enable_fuel_messages"]));
            }
            set {
                this["enable_fuel_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_gap_messages {
            get {
                return ((bool)(this["enable_gap_messages"]));
            }
            set {
                this["enable_gap_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_position_messages {
            get {
                return ((bool)(this["enable_position_messages"]));
            }
            set {
                this["enable_position_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_session_end_messages {
            get {
                return ((bool)(this["enable_session_end_messages"]));
            }
            set {
                this["enable_session_end_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_tyre_wear_warnings {
            get {
                return ((bool)(this["enable_tyre_wear_warnings"]));
            }
            set {
                this["enable_tyre_wear_warnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int spotter_update_interval {
            get {
                return ((int)(this["spotter_update_interval"]));
            }
            set {
                this["spotter_update_interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/games/steam/steamapps/common/pCars/pCARS.exe")]
        public string pcars64_launch_exe {
            get {
                return ((string)(this["pcars64_launch_exe"]));
            }
            set {
                this["pcars64_launch_exe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:/games/steam/steamapps/common/pCars/pCARS.exe")]
        public string pcars32_launch_exe {
            get {
                return ((string)(this["pcars32_launch_exe"]));
            }
            set {
                this["pcars32_launch_exe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pcars64_launch_params {
            get {
                return ((string)(this["pcars64_launch_params"]));
            }
            set {
                this["pcars64_launch_params"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-x86")]
        public string pcars32_launch_params {
            get {
                return ((string)(this["pcars32_launch_params"]));
            }
            set {
                this["pcars32_launch_params"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool launch_pcars {
            get {
                return ((bool)(this["launch_pcars"]));
            }
            set {
                this["launch_pcars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.5")]
        public float pcars_spotter_car_length {
            get {
                return ((float)(this["pcars_spotter_car_length"]));
            }
            set {
                this["pcars_spotter_car_length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string last_game_definition {
            get {
                return ((string)(this["last_game_definition"]));
            }
            set {
                this["last_game_definition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int TOGGLE_READ_OPPONENT_DELTAS_button_index {
            get {
                return ((int)(this["TOGGLE_READ_OPPONENT_DELTAS_button_index"]));
            }
            set {
                this["TOGGLE_READ_OPPONENT_DELTAS_button_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TOGGLE_READ_OPPONENT_DELTAS_device_guid {
            get {
                return ((string)(this["TOGGLE_READ_OPPONENT_DELTAS_device_guid"]));
            }
            set {
                this["TOGGLE_READ_OPPONENT_DELTAS_device_guid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TOGGLE_READ_OPPONENT_DELTAS_device_type {
            get {
                return ((string)(this["TOGGLE_READ_OPPONENT_DELTAS_device_type"]));
            }
            set {
                this["TOGGLE_READ_OPPONENT_DELTAS_device_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_brake_temp_warnings {
            get {
                return ((bool)(this["enable_brake_temp_warnings"]));
            }
            set {
                this["enable_brake_temp_warnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_wheel_spin_warnings {
            get {
                return ((bool)(this["enable_wheel_spin_warnings"]));
            }
            set {
                this["enable_wheel_spin_warnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_brake_lock_warnings {
            get {
                return ((bool)(this["enable_brake_lock_warnings"]));
            }
            set {
                this["enable_brake_lock_warnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool attempt_pcars_opponent_pit_detection {
            get {
                return ((bool)(this["attempt_pcars_opponent_pit_detection"]));
            }
            set {
                this["attempt_pcars_opponent_pit_detection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_green_light_messages {
            get {
                return ((bool)(this["enable_green_light_messages"]));
            }
            set {
                this["enable_green_light_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pcars_steam_id {
            get {
                return ((string)(this["pcars_steam_id"]));
            }
            set {
                this["pcars_steam_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float cumulative_lap_lockup_warning_threshold {
            get {
                return ((float)(this["cumulative_lap_lockup_warning_threshold"]));
            }
            set {
                this["cumulative_lap_lockup_warning_threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float cumulative_lap_wheelspin_warning_threshold {
            get {
                return ((float)(this["cumulative_lap_wheelspin_warning_threshold"]));
            }
            set {
                this["cumulative_lap_wheelspin_warning_threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool use_listen_beep {
            get {
                return ((bool)(this["use_listen_beep"]));
            }
            set {
                this["use_listen_beep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REPEAT_LAST_MESSAGE_BUTTON_device_guid {
            get {
                return ((string)(this["REPEAT_LAST_MESSAGE_BUTTON_device_guid"]));
            }
            set {
                this["REPEAT_LAST_MESSAGE_BUTTON_device_guid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int REPEAT_LAST_MESSAGE_BUTTON_button_index {
            get {
                return ((int)(this["REPEAT_LAST_MESSAGE_BUTTON_button_index"]));
            }
            set {
                this["REPEAT_LAST_MESSAGE_BUTTON_button_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REPEAT_LAST_MESSAGE_BUTTON_device_type {
            get {
                return ((string)(this["REPEAT_LAST_MESSAGE_BUTTON_device_type"]));
            }
            set {
                this["REPEAT_LAST_MESSAGE_BUTTON_device_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_driver_names {
            get {
                return ((bool)(this["enable_driver_names"]));
            }
            set {
                this["enable_driver_names"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public float minimum_name_voice_recognition_confidence {
            get {
                return ((float)(this["minimum_name_voice_recognition_confidence"]));
            }
            set {
                this["minimum_name_voice_recognition_confidence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float minimum_voice_recognition_confidence {
            get {
                return ((float)(this["minimum_voice_recognition_confidence"]));
            }
            set {
                this["minimum_voice_recognition_confidence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool display_session_lap_times {
            get {
                return ((bool)(this["display_session_lap_times"]));
            }
            set {
                this["display_session_lap_times"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int frequency_of_race_sector_delta_reports {
            get {
                return ((int)(this["frequency_of_race_sector_delta_reports"]));
            }
            set {
                this["frequency_of_race_sector_delta_reports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int frequency_of_opponent_race_lap_times {
            get {
                return ((int)(this["frequency_of_opponent_race_lap_times"]));
            }
            set {
                this["frequency_of_opponent_race_lap_times"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int frequency_of_player_race_lap_time_reports {
            get {
                return ((int)(this["frequency_of_player_race_lap_time_reports"]));
            }
            set {
                this["frequency_of_player_race_lap_time_reports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int frequency_of_prac_and_qual_sector_delta_reports {
            get {
                return ((int)(this["frequency_of_prac_and_qual_sector_delta_reports"]));
            }
            set {
                this["frequency_of_prac_and_qual_sector_delta_reports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool race_sector_reports_at_each_sector {
            get {
                return ((bool)(this["race_sector_reports_at_each_sector"]));
            }
            set {
                this["race_sector_reports_at_each_sector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool practice_and_qual_sector_reports_at_each_sector {
            get {
                return ((bool)(this["practice_and_qual_sector_reports_at_each_sector"]));
            }
            set {
                this["practice_and_qual_sector_reports_at_each_sector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool race_sector_reports_at_lap_end {
            get {
                return ((bool)(this["race_sector_reports_at_lap_end"]));
            }
            set {
                this["race_sector_reports_at_lap_end"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool practice_and_qual_sector_reports_at_lap_end {
            get {
                return ((bool)(this["practice_and_qual_sector_reports_at_lap_end"]));
            }
            set {
                this["practice_and_qual_sector_reports_at_lap_end"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int frequency_of_gap_ahead_reports {
            get {
                return ((int)(this["frequency_of_gap_ahead_reports"]));
            }
            set {
                this["frequency_of_gap_ahead_reports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int frequency_of_gap_behind_reports {
            get {
                return ((int)(this["frequency_of_gap_behind_reports"]));
            }
            set {
                this["frequency_of_gap_behind_reports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int frequency_of_car_close_ahead_reports {
            get {
                return ((int)(this["frequency_of_car_close_ahead_reports"]));
            }
            set {
                this["frequency_of_car_close_ahead_reports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int frequency_of_car_close_behind_reports {
            get {
                return ((int)(this["frequency_of_car_close_behind_reports"]));
            }
            set {
                this["frequency_of_car_close_behind_reports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int frequency_of_opponent_practice_and_qual_lap_times {
            get {
                return ((int)(this["frequency_of_opponent_practice_and_qual_lap_times"]));
            }
            set {
                this["frequency_of_opponent_practice_and_qual_lap_times"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enable_track_and_air_temp_reports {
            get {
                return ((bool)(this["enable_track_and_air_temp_reports"]));
            }
            set {
                this["enable_track_and_air_temp_reports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ambient_temp_check_interval_seconds {
            get {
                return ((int)(this["ambient_temp_check_interval_seconds"]));
            }
            set {
                this["ambient_temp_check_interval_seconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int track_temp_check_interval_seconds {
            get {
                return ((int)(this["track_temp_check_interval_seconds"]));
            }
            set {
                this["track_temp_check_interval_seconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float report_ambient_temp_changes_greater_than {
            get {
                return ((float)(this["report_ambient_temp_changes_greater_than"]));
            }
            set {
                this["report_ambient_temp_changes_greater_than"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float report_track_temp_changes_greater_than {
            get {
                return ((float)(this["report_track_temp_changes_greater_than"]));
            }
            set {
                this["report_track_temp_changes_greater_than"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5606")]
        public int udp_data_port {
            get {
                return ((int)(this["udp_data_port"]));
            }
            set {
                this["udp_data_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_damage_messages {
            get {
                return ((bool)(this["enable_damage_messages"]));
            }
            set {
                this["enable_damage_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enable_brake_damage_messages {
            get {
                return ((bool)(this["enable_brake_damage_messages"]));
            }
            set {
                this["enable_brake_damage_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_suspension_damage_messages {
            get {
                return ((bool)(this["enable_suspension_damage_messages"]));
            }
            set {
                this["enable_suspension_damage_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int frequency_of_overtaking_messages {
            get {
                return ((int)(this["frequency_of_overtaking_messages"]));
            }
            set {
                this["frequency_of_overtaking_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int frequency_of_being_overtaken_messages {
            get {
                return ((int)(this["frequency_of_being_overtaken_messages"]));
            }
            set {
                this["frequency_of_being_overtaken_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int frequency_of_player_prac_and_qual_lap_time_reports {
            get {
                return ((int)(this["frequency_of_player_prac_and_qual_lap_time_reports"]));
            }
            set {
                this["frequency_of_player_prac_and_qual_lap_time_reports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool use_alternate_beeps {
            get {
                return ((bool)(this["use_alternate_beeps"]));
            }
            set {
                this["use_alternate_beeps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool disable_pcars_prac_and_qual_pole_deltas {
            get {
                return ((bool)(this["disable_pcars_prac_and_qual_pole_deltas"]));
            }
            set {
                this["disable_pcars_prac_and_qual_pole_deltas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float pause_between_messages {
            get {
                return ((float)(this["pause_between_messages"]));
            }
            set {
                this["pause_between_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_drs_messages {
            get {
                return ((bool)(this["enable_drs_messages"]));
            }
            set {
                this["enable_drs_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_push_to_pass_messages {
            get {
                return ((bool)(this["enable_push_to_pass_messages"]));
            }
            set {
                this["enable_push_to_pass_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool use_fahrenheit {
            get {
                return ((bool)(this["use_fahrenheit"]));
            }
            set {
                this["use_fahrenheit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string override_default_sound_pack_location {
            get {
                return ((string)(this["override_default_sound_pack_location"]));
            }
            set {
                this["override_default_sound_pack_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cache_sounds {
            get {
                return ((bool)(this["cache_sounds"]));
            }
            set {
                this["cache_sounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int min_time_between_personalised_messages {
            get {
                return ((int)(this["min_time_between_personalised_messages"]));
            }
            set {
                this["min_time_between_personalised_messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool load_sound_files_on_startup {
            get {
                return ((bool)(this["load_sound_files_on_startup"]));
            }
            set {
                this["load_sound_files_on_startup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("windows-1252")]
        public string pcars_character_encoding {
            get {
                return ((string)(this["pcars_character_encoding"]));
            }
            set {
                this["pcars_character_encoding"] = value;
            }
        }
    }
}
